version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: /
    schedule:
      interval: daily
    labels:
      - 'skip news'
      - 'code health'

  - package-ecosystem: 'pip'
    directory: /src/test/python_tests
    schedule:
      interval: daily
    labels:
      - 'skip news'
      - 'code health'

  - package-ecosystem: 'pip'
    directory: /
    schedule:
      interval: daily
    labels:
      - 'news'
      - 'code health'
    commit-message:
      include: 'scope'
      prefix: 'pip'

  - package-ecosystem: 'npm'
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'skip news'
      - 'code health'
    ignore:
      - dependency-name: '@types/vscode'
      - dependency-name: '@types/node'
